---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "my-nginx"
  labels:
    nirmata.io/deployment.name: "my-nginx"
    nirmata.io/component: "my-nginx"
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      run: "my-nginx"
      nirmata.io/component: "my-nginx"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        nirmata.io/deployment.name: "my-nginx"
        run: "my-nginx"
        nirmata.io/component: "my-nginx"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "my-nginx"
        image: "nginx"
        command: []
        args: []
        ports:
        - containerPort: 80
          protocol: "TCP"
